//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopwave.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopwave.Localization.Label", typeof(Label).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied !.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Monitoring.
        /// </summary>
        public static string ACTIVITY_MONITOR {
            get {
                return ResourceManager.GetString("ACTIVITY_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Bal. Amount.
        /// </summary>
        public static string ACTUAL_BAL_AMOUNT {
            get {
                return ResourceManager.GetString("ACTUAL_BAL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string ADD_NEW {
            get {
                return ResourceManager.GetString("ADD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment (+).
        /// </summary>
        public static string ADJUSTMENT_IN {
            get {
                return ResourceManager.GetString("ADJUSTMENT_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment (-).
        /// </summary>
        public static string ADJUSTMENT_OUT {
            get {
                return ResourceManager.GetString("ADJUSTMENT_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string ADVANCED_SEARCH {
            get {
                return ResourceManager.GetString("ADVANCED_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string AGE {
            get {
                return ResourceManager.GetString("AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string AGENT {
            get {
                return ResourceManager.GetString("AGENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL {
            get {
                return ResourceManager.GetString("ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AMOUNT {
            get {
                return ResourceManager.GetString("AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AREA {
            get {
                return ResourceManager.GetString("AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string ATTENTION {
            get {
                return ResourceManager.GetString("ATTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string AVAILABILITY {
            get {
                return ResourceManager.GetString("AVAILABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BALANCE {
            get {
                return ResourceManager.GetString("BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string BANK {
            get {
                return ResourceManager.GetString("BANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Acc. No..
        /// </summary>
        public static string BANK_ACC_NO {
            get {
                return ResourceManager.GetString("BANK_ACC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Host.
        /// </summary>
        public static string BANK_HOST {
            get {
                return ResourceManager.GetString("BANK_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch No.
        /// </summary>
        public static string BATCH_NO {
            get {
                return ResourceManager.GetString("BATCH_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string BONUS {
            get {
                return ResourceManager.GetString("BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hour.
        /// </summary>
        public static string BUSINESS_HOUR {
            get {
                return ResourceManager.GetString("BUSINESS_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Description.
        /// </summary>
        public static string BY_DESCRIPTION {
            get {
                return ResourceManager.GetString("BY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Item.
        /// </summary>
        public static string BY_ITEM {
            get {
                return ResourceManager.GetString("BY_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Login Type.
        /// </summary>
        public static string BY_LOGIN_TYPE {
            get {
                return ResourceManager.GetString("BY_LOGIN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Race.
        /// </summary>
        public static string BY_RACE {
            get {
                return ResourceManager.GetString("BY_RACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Code.
        /// </summary>
        public static string CAMPAIGN_CODE {
            get {
                return ResourceManager.GetString("CAMPAIGN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Type.
        /// </summary>
        public static string CAMPAIGN_TYPE {
            get {
                return ResourceManager.GetString("CAMPAIGN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string CATALOG {
            get {
                return ResourceManager.GetString("CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Filter.
        /// </summary>
        public static string CLEAR_ALL_FILTER {
            get {
                return ResourceManager.GetString("CLEAR_ALL_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.O.D.
        /// </summary>
        public static string COD {
            get {
                return ResourceManager.GetString("COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string COMPANY_NAME {
            get {
                return ResourceManager.GetString("COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile.
        /// </summary>
        public static string COMPANY_PROFILE {
            get {
                return ResourceManager.GetString("COMPANY_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee Name (E).
        /// </summary>
        public static string CONSIGNEE_NAME_EN {
            get {
                return ResourceManager.GetString("CONSIGNEE_NAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignee Sales Entry.
        /// </summary>
        public static string CONSIGNEE_SALES_ENTRY {
            get {
                return ResourceManager.GetString("CONSIGNEE_SALES_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment Invoice.
        /// </summary>
        public static string CONSIGNMENT_INVOICE {
            get {
                return ResourceManager.GetString("CONSIGNMENT_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignment Note.
        /// </summary>
        public static string CONSIGNMENT_NOTE {
            get {
                return ResourceManager.GetString("CONSIGNMENT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN Date.
        /// </summary>
        public static string CREDIT_NOTE_DATE {
            get {
                return ResourceManager.GetString("CREDIT_NOTE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN No.
        /// </summary>
        public static string CREDIT_NOTE_NO {
            get {
                return ResourceManager.GetString("CREDIT_NOTE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Used Analysis.
        /// </summary>
        public static string CREDIT_USED_ANALYSIS {
            get {
                return ResourceManager.GetString("CREDIT_USED_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CURRENCY_CODE {
            get {
                return ResourceManager.GetString("CURRENCY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        public static string CURRENCY_SYMBOL {
            get {
                return ResourceManager.GetString("CURRENCY_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Word.
        /// </summary>
        public static string CURRENCY_WORD {
            get {
                return ResourceManager.GetString("CURRENCY_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/C No.
        /// </summary>
        public static string CUST_ACC_NO {
            get {
                return ResourceManager.GetString("CUST_ACC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name (C).
        /// </summary>
        public static string CUST_NAME_C {
            get {
                return ResourceManager.GetString("CUST_NAME_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name (E).
        /// </summary>
        public static string CUST_NAME_E {
            get {
                return ResourceManager.GetString("CUST_NAME_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CUSTOMER {
            get {
                return ResourceManager.GetString("CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CUSTOMER_CODE {
            get {
                return ResourceManager.GetString("CUSTOMER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Data Path.
        /// </summary>
        public static string CUSTOMER_DATA_PATH {
            get {
                return ResourceManager.GetString("CUSTOMER_DATA_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Stock Balance.
        /// </summary>
        public static string DAILY_STOCK_BALANCE {
            get {
                return ResourceManager.GetString("DAILY_STOCK_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Transaction.
        /// </summary>
        public static string DAILY_TRANSACTION {
            get {
                return ResourceManager.GetString("DAILY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Trend.
        /// </summary>
        public static string DAILY_TREND {
            get {
                return ResourceManager.GetString("DAILY_TREND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DASHBOARD {
            get {
                return ResourceManager.GetString("DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Note.
        /// </summary>
        public static string DEBIT_NOTE {
            get {
                return ResourceManager.GetString("DEBIT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN Date.
        /// </summary>
        public static string DEBIT_NOTE_DATE {
            get {
                return ResourceManager.GetString("DEBIT_NOTE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN No.
        /// </summary>
        public static string DEBIT_NOTE_NO {
            get {
                return ResourceManager.GetString("DEBIT_NOTE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DELETE_SELECTED {
            get {
                return ResourceManager.GetString("DELETE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO Date.
        /// </summary>
        public static string DELIVERY_ORDER_DATE {
            get {
                return ResourceManager.GetString("DELIVERY_ORDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO No.
        /// </summary>
        public static string DELIVERY_ORDER_NO {
            get {
                return ResourceManager.GetString("DELIVERY_ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DEPOSIT {
            get {
                return ResourceManager.GetString("DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string DEPTH {
            get {
                return ResourceManager.GetString("DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION (C).
        /// </summary>
        public static string DESCRIPTION_CH {
            get {
                return ResourceManager.GetString("DESCRIPTION_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION (E).
        /// </summary>
        public static string DESCRIPTION_EN {
            get {
                return ResourceManager.GetString("DESCRIPTION_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despatch List.
        /// </summary>
        public static string DESPATCH_LIST {
            get {
                return ResourceManager.GetString("DESPATCH_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension UM.
        /// </summary>
        public static string DIMENSION_UM {
            get {
                return ResourceManager.GetString("DIMENSION_UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        public static string DISCOUNT_AMOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disp. Qty.
        /// </summary>
        public static string DISPLAY_QTY {
            get {
                return ResourceManager.GetString("DISPLAY_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO Qty.
        /// </summary>
        public static string DO_QTY {
            get {
                return ResourceManager.GetString("DO_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DOC_TYPE {
            get {
                return ResourceManager.GetString("DOC_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Matrix Printer.
        /// </summary>
        public static string DOTMATRIX_PRINTER {
            get {
                return ResourceManager.GetString("DOTMATRIX_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EMPLOYEE {
            get {
                return ResourceManager.GetString("EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string EXPIRED {
            get {
                return ResourceManager.GetString("EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string EXPIRY_DATE {
            get {
                return ResourceManager.GetString("EXPIRY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax/Telex.
        /// </summary>
        public static string FAX_O_TELEX {
            get {
                return ResourceManager.GetString("FAX_O_TELEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocess Grab-It Summary.
        /// </summary>
        public static string FLOATING_SUMM {
            get {
                return ResourceManager.GetString("FLOATING_SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string FORGOT_PASS {
            get {
                return ResourceManager.GetString("FORGOT_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free gift.
        /// </summary>
        public static string FREE_GIFT {
            get {
                return ResourceManager.GetString("FREE_GIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FROM_DATE {
            get {
                return ResourceManager.GetString("FROM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice.
        /// </summary>
        public static string GENERATE_INVOICE {
            get {
                return ResourceManager.GetString("GENERATE_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Location.
        /// </summary>
        public static string GEO_LOCATION {
            get {
                return ResourceManager.GetString("GEO_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Bonus.
        /// </summary>
        public static string GOLD_LEVEL_BONUS {
            get {
                return ResourceManager.GetString("GOLD_LEVEL_BONUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Location.
        /// </summary>
        public static string GPS_LOC {
            get {
                return ResourceManager.GetString("GPS_LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Amount.
        /// </summary>
        public static string GROSS_AMT {
            get {
                return ResourceManager.GetString("GROSS_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Batch No.
        /// </summary>
        public static string GROUP_BY_BATCH_NO {
            get {
                return ResourceManager.GetString("GROUP_BY_BATCH_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Product Code.
        /// </summary>
        public static string GROUP_BY_PRODUCT_CODE {
            get {
                return ResourceManager.GetString("GROUP_BY_PRODUCT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        public static string GST {
            get {
                return ResourceManager.GetString("GST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HELLO {
            get {
                return ResourceManager.GetString("HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC No.
        /// </summary>
        public static string IC_NO {
            get {
                return ResourceManager.GetString("IC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-activate.
        /// </summary>
        public static string IN_ACTIVATE {
            get {
                return ResourceManager.GetString("IN_ACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string IN_ACTIVE {
            get {
                return ResourceManager.GetString("IN_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inn Name.
        /// </summary>
        public static string INN_NAME {
            get {
                return ResourceManager.GetString("INN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Blank.
        /// </summary>
        public static string INSERT_BLANK {
            get {
                return ResourceManager.GetString("INSERT_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string INVOICE {
            get {
                return ResourceManager.GetString("INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string INVOICE_DATE {
            get {
                return ResourceManager.GetString("INVOICE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice History.
        /// </summary>
        public static string INVOICE_HISTORY {
            get {
                return ResourceManager.GetString("INVOICE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string INVOICE_NO {
            get {
                return ResourceManager.GetString("INVOICE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Qty.
        /// </summary>
        public static string INVOICE_QTY {
            get {
                return ResourceManager.GetString("INVOICE_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active ?.
        /// </summary>
        public static string IS_ACTIVE {
            get {
                return ResourceManager.GetString("IS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Consignment?.
        /// </summary>
        public static string IS_CONSIGNMENT {
            get {
                return ResourceManager.GetString("IS_CONSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Size.
        /// </summary>
        public static string ITEM_SIZE {
            get {
                return ResourceManager.GetString("ITEM_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Under.
        /// </summary>
        public static string JOIN_UNDER {
            get {
                return ResourceManager.GetString("JOIN_UNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined.
        /// </summary>
        public static string JOINED {
            get {
                return ResourceManager.GetString("JOINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Date.
        /// </summary>
        public static string JOINED_DATE {
            get {
                return ResourceManager.GetString("JOINED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.I.V.
        /// </summary>
        public static string KICK_IN_VIEW {
            get {
                return ResourceManager.GetString("KICK_IN_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Measurement.
        /// </summary>
        public static string LARGE_MEASUREMENT {
            get {
                return ResourceManager.GetString("LARGE_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Expiry Date.
        /// </summary>
        public static string LICENSE_EXP_DATE {
            get {
                return ResourceManager.GetString("LICENSE_EXP_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string LIMIT {
            get {
                return ResourceManager.GetString("LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LOCATION {
            get {
                return ResourceManager.GetString("LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LOG_IN {
            get {
                return ResourceManager.GetString("LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LOG_OUT {
            get {
                return ResourceManager.GetString("LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        public static string M3 {
            get {
                return ResourceManager.GetString("M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Dashbord.
        /// </summary>
        public static string MAIN_DASHBOARD {
            get {
                return ResourceManager.GetString("MAIN_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data Management.
        /// </summary>
        public static string MASTER_DATA {
            get {
                return ResourceManager.GetString("MASTER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Measurement.
        /// </summary>
        public static string MEDIUM_MEASUREMENT {
            get {
                return ResourceManager.GetString("MEDIUM_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string MEMBER {
            get {
                return ResourceManager.GetString("MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Code.
        /// </summary>
        public static string MEMBER_CODE {
            get {
                return ResourceManager.GetString("MEMBER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for Members.
        /// </summary>
        public static string MEMBER_DASHBOARD {
            get {
                return ResourceManager.GetString("MEMBER_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string MEMBER_NAME {
            get {
                return ResourceManager.GetString("MEMBER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Payment.
        /// </summary>
        public static string MEMBER_PAYMENT {
            get {
                return ResourceManager.GetString("MEMBER_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Statistic.
        /// </summary>
        public static string MEMBER_STATISTIC {
            get {
                return ResourceManager.GetString("MEMBER_STATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Ref..
        /// </summary>
        public static string MERCHANT_REF {
            get {
                return ResourceManager.GetString("MERCHANT_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MOBILE_NO {
            get {
                return ResourceManager.GetString("MOBILE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string MODULE_NAME {
            get {
                return ResourceManager.GetString("MODULE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year.
        /// </summary>
        public static string MONTH_YEAR {
            get {
                return ResourceManager.GetString("MONTH_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Active Outlets.
        /// </summary>
        public static string MOST_ACTIVE_OUTLET {
            get {
                return ResourceManager.GetString("MOST_ACTIVE_OUTLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top InActive Outlets.
        /// </summary>
        public static string MOST_INACTIVE_OUTLET {
            get {
                return ResourceManager.GetString("MOST_INACTIVE_OUTLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transaction.
        /// </summary>
        public static string MY_TRANSACTION {
            get {
                return ResourceManager.GetString("MY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature Of Business.
        /// </summary>
        public static string NATURE_OF_BUSINESS {
            get {
                return ResourceManager.GetString("NATURE_OF_BUSINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        public static string NET_AMT {
            get {
                return ResourceManager.GetString("NET_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nett.
        /// </summary>
        public static string NETT {
            get {
                return ResourceManager.GetString("NETT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature Of Business.
        /// </summary>
        public static string NOB {
            get {
                return ResourceManager.GetString("NOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NORMAL {
            get {
                return ResourceManager.GetString("NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Printer.
        /// </summary>
        public static string OTHER_PRINTER {
            get {
                return ResourceManager.GetString("OTHER_PRINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Ref.
        /// </summary>
        public static string OTHER_REF {
            get {
                return ResourceManager.GetString("OTHER_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OTHERS {
            get {
                return ResourceManager.GetString("OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet.
        /// </summary>
        public static string OUTLET {
            get {
                return ResourceManager.GetString("OUTLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Code.
        /// </summary>
        public static string OUTLET_CODE {
            get {
                return ResourceManager.GetString("OUTLET_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Listing.
        /// </summary>
        public static string OUTLET_LISTING {
            get {
                return ResourceManager.GetString("OUTLET_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Name.
        /// </summary>
        public static string OUTLET_NAME {
            get {
                return ResourceManager.GetString("OUTLET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC No.
        /// </summary>
        public static string PAC_NO {
            get {
                return ResourceManager.GetString("PAC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Qty.
        /// </summary>
        public static string PACK_QTY {
            get {
                return ResourceManager.GetString("PACK_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Type.
        /// </summary>
        public static string PACK_TYPE {
            get {
                return ResourceManager.GetString("PACK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing List.
        /// </summary>
        public static string PACKING_LIST {
            get {
                return ResourceManager.GetString("PACKING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Break.
        /// </summary>
        public static string PAGE_BREAK {
            get {
                return ResourceManager.GetString("PAGE_BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string PAYER {
            get {
                return ResourceManager.GetString("PAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        public static string PAYMENT_DATE {
            get {
                return ResourceManager.GetString("PAYMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Ref.
        /// </summary>
        public static string PAYMENT_REF {
            get {
                return ResourceManager.GetString("PAYMENT_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Reject.
        /// </summary>
        public static string PAYMENT_REJECT {
            get {
                return ResourceManager.GetString("PAYMENT_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PAYMENT_TYPE {
            get {
                return ResourceManager.GetString("PAYMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Qty.
        /// </summary>
        public static string PENDING_QTY {
            get {
                return ResourceManager.GetString("PENDING_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacist.
        /// </summary>
        public static string PHARMACIST {
            get {
                return ResourceManager.GetString("PHARMACIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        public static string PHONE_1 {
            get {
                return ResourceManager.GetString("PHONE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        public static string PHONE_2 {
            get {
                return ResourceManager.GetString("PHONE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Ref No.
        /// </summary>
        public static string PO_REF_NO {
            get {
                return ResourceManager.GetString("PO_REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string POINT {
            get {
                return ResourceManager.GetString("POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Issue Summary.
        /// </summary>
        public static string POINT_ISSUE_SUMM {
            get {
                return ResourceManager.GetString("POINT_ISSUE_SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Transaction Listing.
        /// </summary>
        public static string POINT_TRANS_LISTING {
            get {
                return ResourceManager.GetString("POINT_TRANS_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Transaction.
        /// </summary>
        public static string POINT_TRANSACTION {
            get {
                return ResourceManager.GetString("POINT_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Type.
        /// </summary>
        public static string POINT_TYPE {
            get {
                return ResourceManager.GetString("POINT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison No.
        /// </summary>
        public static string POISON_NO {
            get {
                return ResourceManager.GetString("POISON_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Report.
        /// </summary>
        public static string POISON_REPORT {
            get {
                return ResourceManager.GetString("POISON_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Signed Order.
        /// </summary>
        public static string POISON_SIGN_ORDER {
            get {
                return ResourceManager.GetString("POISON_SIGN_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Whole Sale Record.
        /// </summary>
        public static string POISON_WHOLESALE {
            get {
                return ResourceManager.GetString("POISON_WHOLESALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string POST {
            get {
                return ResourceManager.GetString("POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post To UBS.
        /// </summary>
        public static string POST_TO_UBS {
            get {
                return ResourceManager.GetString("POST_TO_UBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string POSTCODE {
            get {
                return ResourceManager.GetString("POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Date.
        /// </summary>
        public static string POSTED_DATE {
            get {
                return ResourceManager.GetString("POSTED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PREVIEW {
            get {
                return ResourceManager.GetString("PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (L).
        /// </summary>
        public static string PRICE_L {
            get {
                return ResourceManager.GetString("PRICE_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (M).
        /// </summary>
        public static string PRICE_M {
            get {
                return ResourceManager.GetString("PRICE_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (S).
        /// </summary>
        public static string PRICE_S {
            get {
                return ResourceManager.GetString("PRICE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PRINT {
            get {
                return ResourceManager.GetString("PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Poision SO.
        /// </summary>
        public static string PRINT_POISION {
            get {
                return ResourceManager.GetString("PRINT_POISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Setting.
        /// </summary>
        public static string PRINTER_SETTING {
            get {
                return ResourceManager.GetString("PRINTER_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procurement.
        /// </summary>
        public static string PRODUCREMENT {
            get {
                return ResourceManager.GetString("PRODUCREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Batch Setup.
        /// </summary>
        public static string PRODUCT_BATCH_SETUP {
            get {
                return ResourceManager.GetString("PRODUCT_BATCH_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Category.
        /// </summary>
        public static string PRODUCT_CATEGORY {
            get {
                return ResourceManager.GetString("PRODUCT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string PRODUCT_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Pack Size.
        /// </summary>
        public static string PRODUCT_PACK_SIZE {
            get {
                return ResourceManager.GetString("PRODUCT_PACK_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Setup.
        /// </summary>
        public static string PRODUCT_SETUP {
            get {
                return ResourceManager.GetString("PRODUCT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose For.
        /// </summary>
        public static string PURPOSE_FOR {
            get {
                return ResourceManager.GetString("PURPOSE_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(+)(L).
        /// </summary>
        public static string QTY_IN_L {
            get {
                return ResourceManager.GetString("QTY_IN_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(+)(M).
        /// </summary>
        public static string QTY_IN_M {
            get {
                return ResourceManager.GetString("QTY_IN_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(+)(S).
        /// </summary>
        public static string QTY_IN_S {
            get {
                return ResourceManager.GetString("QTY_IN_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty (L).
        /// </summary>
        public static string QTY_L {
            get {
                return ResourceManager.GetString("QTY_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty (M).
        /// </summary>
        public static string QTY_M {
            get {
                return ResourceManager.GetString("QTY_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(-)(L).
        /// </summary>
        public static string QTY_OUT_L {
            get {
                return ResourceManager.GetString("QTY_OUT_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(-)(M).
        /// </summary>
        public static string QTY_OUT_M {
            get {
                return ResourceManager.GetString("QTY_OUT_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty(-)(S).
        /// </summary>
        public static string QTY_OUT_S {
            get {
                return ResourceManager.GetString("QTY_OUT_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty (S).
        /// </summary>
        public static string QTY_S {
            get {
                return ResourceManager.GetString("QTY_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string REASON {
            get {
                return ResourceManager.GetString("REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Qty (L).
        /// </summary>
        public static string REC_QTY_L {
            get {
                return ResourceManager.GetString("REC_QTY_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Qty (M).
        /// </summary>
        public static string REC_QTY_M {
            get {
                return ResourceManager.GetString("REC_QTY_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Qty (S).
        /// </summary>
        public static string REC_QTY_S {
            get {
                return ResourceManager.GetString("REC_QTY_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Date.
        /// </summary>
        public static string RECEIVE_DATE {
            get {
                return ResourceManager.GetString("RECEIVE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption Summary.
        /// </summary>
        public static string REDEMPTION_SUMM {
            get {
                return ResourceManager.GetString("REDEMPTION_SUMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption Type.
        /// </summary>
        public static string REDEMPTION_TYPE {
            get {
                return ResourceManager.GetString("REDEMPTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Date.
        /// </summary>
        public static string REF_DATE {
            get {
                return ResourceManager.GetString("REF_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. No.
        /// </summary>
        public static string REF_NO {
            get {
                return ResourceManager.GetString("REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration No.
        /// </summary>
        public static string REG_NO {
            get {
                return ResourceManager.GetString("REG_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string REGION {
            get {
                return ResourceManager.GetString("REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string REJECT {
            get {
                return ResourceManager.GetString("REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string REMARKS {
            get {
                return ResourceManager.GetString("REMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string REPORT_TYPE {
            get {
                return ResourceManager.GetString("REPORT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        public static string REPORTING {
            get {
                return ResourceManager.GetString("REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request PAC.
        /// </summary>
        public static string REQUEST_PIN {
            get {
                return ResourceManager.GetString("REQUEST_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string RESET_PASS {
            get {
                return ResourceManager.GetString("RESET_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Inward.
        /// </summary>
        public static string RETURN_INWARD {
            get {
                return ResourceManager.GetString("RETURN_INWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Inward Date.
        /// </summary>
        public static string RETURN_INWARD_DATE {
            get {
                return ResourceManager.GetString("RETURN_INWARD_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Inward No.
        /// </summary>
        public static string RETURN_INWARD_NO {
            get {
                return ResourceManager.GetString("RETURN_INWARD_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Qty.
        /// </summary>
        public static string RETURN_QTY {
            get {
                return ResourceManager.GetString("RETURN_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Number.
        /// </summary>
        public static string RUNNING_NUMBER {
            get {
                return ResourceManager.GetString("RUNNING_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Adjustment Reason.
        /// </summary>
        public static string SA_REASON {
            get {
                return ResourceManager.GetString("SA_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default display in Stock In ?.
        /// </summary>
        public static string SA_REASON_DEFAULT {
            get {
                return ResourceManager.GetString("SA_REASON_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Date.
        /// </summary>
        public static string SALES_DATE {
            get {
                return ResourceManager.GetString("SALES_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales History Report.
        /// </summary>
        public static string SALES_HIST_REPORT {
            get {
                return ResourceManager.GetString("SALES_HIST_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales History.
        /// </summary>
        public static string SALES_HISTORY {
            get {
                return ResourceManager.GetString("SALES_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        public static string SALES_INVOICE {
            get {
                return ResourceManager.GetString("SALES_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Ref. No.
        /// </summary>
        public static string SALES_REF_NO {
            get {
                return ResourceManager.GetString("SALES_REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Type.
        /// </summary>
        public static string SALES_TYPE {
            get {
                return ResourceManager.GetString("SALES_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Order.
        /// </summary>
        public static string SAMPLE_ORDER {
            get {
                return ResourceManager.GetString("SAMPLE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Order Date.
        /// </summary>
        public static string SAMPLE_ORDER_DATE {
            get {
                return ResourceManager.GetString("SAMPLE_ORDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Order No.
        /// </summary>
        public static string SAMPLE_ORDER_NO {
            get {
                return ResourceManager.GetString("SAMPLE_ORDER_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save With Invoice ?.
        /// </summary>
        public static string SAVE_WITH_INVOICE {
            get {
                return ResourceManager.GetString("SAVE_WITH_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To.
        /// </summary>
        public static string SHIP_TO {
            get {
                return ResourceManager.GetString("SHIP_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship To Different Address.
        /// </summary>
        public static string SHIP_TO_DIFF_ADD {
            get {
                return ResourceManager.GetString("SHIP_TO_DIFF_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        public static string SHIPMENT {
            get {
                return ResourceManager.GetString("SHIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Date.
        /// </summary>
        public static string SHIPMENT_DATE {
            get {
                return ResourceManager.GetString("SHIPMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Note.
        /// </summary>
        public static string SHIPMENT_NOTE {
            get {
                return ResourceManager.GetString("SHIPMENT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Measurement.
        /// </summary>
        public static string SMALL_MEASUREMENT {
            get {
                return ResourceManager.GetString("SMALL_MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string SPONSOR {
            get {
                return ResourceManager.GetString("SPONSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor By.
        /// </summary>
        public static string SPONSOR_BY {
            get {
                return ResourceManager.GetString("SPONSOR_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Point.
        /// </summary>
        public static string SPONSOR_POINT {
            get {
                return ResourceManager.GetString("SPONSOR_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor To.
        /// </summary>
        public static string SPONSOR_TO {
            get {
                return ResourceManager.GetString("SPONSOR_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Adjustment.
        /// </summary>
        public static string STOCK_ADJUSTMENT {
            get {
                return ResourceManager.GetString("STOCK_ADJUSTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Adjustment Reason.
        /// </summary>
        public static string STOCK_ADJUSTMENT_REASON {
            get {
                return ResourceManager.GetString("STOCK_ADJUSTMENT_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Balance.
        /// </summary>
        public static string STOCK_BALANCE {
            get {
                return ResourceManager.GetString("STOCK_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock In.
        /// </summary>
        public static string STOCK_IN {
            get {
                return ResourceManager.GetString("STOCK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock KIV.
        /// </summary>
        public static string STOCK_KIV {
            get {
                return ResourceManager.GetString("STOCK_KIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Movement.
        /// </summary>
        public static string STOCK_MOVEMENT {
            get {
                return ResourceManager.GetString("STOCK_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out.
        /// </summary>
        public static string STOCK_OUT {
            get {
                return ResourceManager.GetString("STOCK_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string STRENGTH {
            get {
                return ResourceManager.GetString("STRENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SYSTEM {
            get {
                return ResourceManager.GetString("SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Setting.
        /// </summary>
        public static string SYSTEM_SETTING {
            get {
                return ResourceManager.GetString("SYSTEM_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string TERM {
            get {
                return ResourceManager.GetString("TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal ID.
        /// </summary>
        public static string TERMINAL_ID {
            get {
                return ResourceManager.GetString("TERMINAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Type.
        /// </summary>
        public static string TERMINAL_TYPE {
            get {
                return ResourceManager.GetString("TERMINAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TERMS {
            get {
                return ResourceManager.GetString("TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string TO_DATE {
            get {
                return ResourceManager.GetString("TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string TOTAL_AMT {
            get {
                return ResourceManager.GetString("TOTAL_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Depth.
        /// </summary>
        public static string TOTAL_DEPTH {
            get {
                return ResourceManager.GetString("TOTAL_DEPTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Height.
        /// </summary>
        public static string TOTAL_HEIGHT {
            get {
                return ResourceManager.GetString("TOTAL_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total M3.
        /// </summary>
        public static string TOTAL_M3 {
            get {
                return ResourceManager.GetString("TOTAL_M3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pack.
        /// </summary>
        public static string TOTAL_PACK {
            get {
                return ResourceManager.GetString("TOTAL_PACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Qty.
        /// </summary>
        public static string TOTAL_QTY {
            get {
                return ResourceManager.GetString("TOTAL_QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight.
        /// </summary>
        public static string TOTAL_WEIGHT {
            get {
                return ResourceManager.GetString("TOTAL_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Width.
        /// </summary>
        public static string TOTAL_WIDTH {
            get {
                return ResourceManager.GetString("TOTAL_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TRANSACTION {
            get {
                return ResourceManager.GetString("TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans. Amt.
        /// </summary>
        public static string TRANSACTION_AMT {
            get {
                return ResourceManager.GetString("TRANSACTION_AMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TRANSACTION_DATE {
            get {
                return ResourceManager.GetString("TRANSACTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Listing.
        /// </summary>
        public static string TRANSACTION_LISTING {
            get {
                return ResourceManager.GetString("TRANSACTION_LISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Posting Path.
        /// </summary>
        public static string TRANSACTION_POST_PATH {
            get {
                return ResourceManager.GetString("TRANSACTION_POST_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string TRANSACTION_TYPE {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TRANSFER {
            get {
                return ResourceManager.GetString("TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Point.
        /// </summary>
        public static string TRANSFER_POINT {
            get {
                return ResourceManager.GetString("TRANSFER_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trasnfer To.
        /// </summary>
        public static string TRANSFER_TO {
            get {
                return ResourceManager.GetString("TRANSFER_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporter.
        /// </summary>
        public static string TRANSPORTER {
            get {
                return ResourceManager.GetString("TRANSPORTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Return Account Code.
        /// </summary>
        public static string UBS_RETURN_CODE {
            get {
                return ResourceManager.GetString("UBS_RETURN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Account Code.
        /// </summary>
        public static string UBS_SALES_CODE {
            get {
                return ResourceManager.GetString("UBS_SALES_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBS Integration Setting.
        /// </summary>
        public static string UBS_SETTING {
            get {
                return ResourceManager.GetString("UBS_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UNIT_PRICE {
            get {
                return ResourceManager.GetString("UNIT_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-post.
        /// </summary>
        public static string UNPOST {
            get {
                return ResourceManager.GetString("UNPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM Conv.
        /// </summary>
        public static string UOM_CONVERSION {
            get {
                return ResourceManager.GetString("UOM_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM (L).
        /// </summary>
        public static string UOM_L {
            get {
                return ResourceManager.GetString("UOM_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM (M).
        /// </summary>
        public static string UOM_M {
            get {
                return ResourceManager.GetString("UOM_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string UPDATED_BY {
            get {
                return ResourceManager.GetString("UPDATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        public static string UPDATED_DATE {
            get {
                return ResourceManager.GetString("UPDATED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string USED {
            get {
                return ResourceManager.GetString("USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string USER_ROLES {
            get {
                return ResourceManager.GetString("USER_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit By.
        /// </summary>
        public static string VISIT_BY {
            get {
                return ResourceManager.GetString("VISIT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit By Female Member.
        /// </summary>
        public static string VISIT_BY_FEMALE {
            get {
                return ResourceManager.GetString("VISIT_BY_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit By Male Member.
        /// </summary>
        public static string VISIT_BY_MALE {
            get {
                return ResourceManager.GetString("VISIT_BY_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WEBSITE {
            get {
                return ResourceManager.GetString("WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WIDTH {
            get {
                return ResourceManager.GetString("WIDTH", resourceCulture);
            }
        }
    }
}
