//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMLM.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMLM.Localization.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not authorize to access..
        /// </summary>
        internal static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go back.
        /// </summary>
        internal static string CLICK_HERE_TO_GO_BACK {
            get {
                return ResourceManager.GetString("CLICK_HERE_TO_GO_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your record(s) was delete successful !.
        /// </summary>
        internal static string DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code.
        /// </summary>
        internal static string INVALID_CAPTCHA_CODE {
            get {
                return ResourceManager.GetString("INVALID_CAPTCHA_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided current password is incorrect..
        /// </summary>
        internal static string INVALID_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. We could not found the outlet of user..
        /// </summary>
        internal static string INVALID_OUTLET {
            get {
                return ResourceManager.GetString("INVALID_OUTLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  password provided is incorrect..
        /// </summary>
        internal static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PAC No..
        /// </summary>
        internal static string INVALID_PIN {
            get {
                return ResourceManager.GetString("INVALID_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The  user name or password provided is incorrect..
        /// </summary>
        internal static string INVALID_USERNAME_O_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_USERNAME_O_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successful !.
        /// </summary>
        internal static string PASSWORD_CHANGE_SUCCESS {
            get {
                return ResourceManager.GetString("PASSWORD_CHANGE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was not match..
        /// </summary>
        internal static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed as this record was referenced by other element..
        /// </summary>
        internal static string RECORD_REFERENCED_ERROR {
            get {
                return ResourceManager.GetString("RECORD_REFERENCED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        internal static string REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset and a temporary password already sent to this mobile number {0}..
        /// </summary>
        internal static string RESET_PASS_MSG {
            get {
                return ResourceManager.GetString("RESET_PASS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your record was saved successful !.
        /// </summary>
        internal static string SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: {0}
        ///Password: {1}.
        /// </summary>
        internal static string SMS_REG_MSG {
            get {
                return ResourceManager.GetString("SMS_REG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal error and was unable to complete your request..
        /// </summary>
        internal static string SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. We could not found the user that you keyed in..
        /// </summary>
        internal static string USER_NAME_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_NAME_NOT_EXIST", resourceCulture);
            }
        }
    }
}
